name: Deploy New_Timeless via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftp.spec-ng.com
          username: jemsenator@spec-ng.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/timeless/
