name: Deploy New_Timeless via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ftp.spec-ng.com
          username: developers@spec-ng.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # set this to where index.html is
          server-dir: /public_html/timeless/
